spring.datasource.url=${VD2_DB_URL:jdbc:sqlserver://localhost:1433;databaseName=security_vd2;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
